#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.23a
#  in conjunction with Tcl version 8.6
#    Jun 26, 2019 11:51:20 AM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global gesto1
    gesto1 = tk.StringVar()
    global gesto2
    gesto2 = tk.StringVar()
    global gesto3
    gesto3 = tk.StringVar()
    global gesto4
    gesto4 = tk.StringVar()
    global gesto5
    gesto5 = tk.StringVar()
    global gesto6
    gesto6 = tk.StringVar()
    global gesto7
    gesto7 = tk.StringVar()
    global gesto8
    gesto8 = tk.StringVar()
    global gesto9
    gesto9 = tk.StringVar()
    global gesto10
    gesto10 = tk.StringVar()
    global gesto11
    gesto11 = tk.StringVar()
    global gesto12
    gesto12 = tk.StringVar()

def destroy_window():
    print('estudios_support.destroy_window')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import estudios
    estudios.vp_start_gui()




